#cloud-config
# Этот файл используется cloud-init для настройки ВМ после первого запуска.

users:
  - name: yc-user
    groups: [ 'sudo', 'docker' ]
    shell: /bin/bash
    sudo: [ 'ALL=(ALL) NOPASSWD:ALL' ]

package_update: true
package_upgrade: true

packages:
  - docker.io         # Устанавливаем сам Docker Engine
  - docker-compose-v2 # Устанавливаем Docker Compose V2 (как плагин)

runcmd:
  # Устанавливаем YC CLI
  - curl -sSL https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash -s -- -a -n
  # Инициализируем yc, чтобы он создал конфиг из метаданных сервисного аккаунта
  - /home/yc-user/yandex-cloud/bin/yc config set cloud-id $(curl -s -H "Metadata-Flavor: Google" http://169.254.169.254/computeMetadata/v1/project/project-id)
  - /home/yc-user/yandex-cloud/bin/yc config set folder-id $(curl -s -H "Metadata-Flavor: Google" http://169.254.169.254/computeMetadata/v1/instance/folder-id)
  # Тут можно добавить команды для клонирования вашего репозитория и запуска docker-compose
  # - su - yc-user -c "git clone <your-repo-url> /home/yc-user/app"
  # - su - yc-user -c "cd /home/yc-user/app/docker-python3.12 && docker-compose up -d"