
services:
  calculator-prod:
    container_name: python-solver
    image: gayrat/python-app-yandex:latest
    networks:
      - app-network
  nodejs:
    container_name: nodejs
    image: gayrat/nodejs-app-yandex:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "3000:3000"
      - "8000:8000"
    depends_on:
      - calculator-prod

    networks:
      - app-network

networks:
  app-network:
    driver: bridge
