
services:
  calculator:
    build:
      context: ./python-app
      dockerfile: Dockerfile
    container_name: python-solver
    
    networks:
      - app-network

  nodejs:
    build:
      context: ./nodejs-app
      dockerfile: Dockerfile
    container_name: nodejs
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
