# F:/_prg/python/OR-Tools-MILP/docker-python3.12/docker-compose.yml
version: '3.8'

services:
  calculator:
    build: .
    container_name: calculator
    # Пример команды для запуска вашего расчета
    # command: ["python", "run_calculation.py", "--param1", "value1"]
    # Монтируем конфигурацию YC CLI из VM в контейнер
    volumes:
      - ~/.config/yandex-cloud:/home/appuser/.config/yandex-cloud:ro

  supervisor:
    build: .
    container_name: supervisor
    command: ["watch-and-destroy.sh", "calculator", "4h"] # Наблюдать за 'calculator' с таймаутом 4 часа
    restart: "no" # Не перезапускать супервизора
    volumes:
      # Доступ к Docker socket для мониторинга контейнеров
      - /var/run/docker.sock:/var/run/docker.sock
      # Монтируем конфигурацию YC CLI
      - ~/.config/yandex-cloud:/home/appuser/.config/yandex-cloud:ro
    depends_on:
      - calculator
