
services:
  calculator-dev:
    build:
      context: ./python-app
      dockerfile: Dockerfile


    volumes:
      # Bind mount для разработки: связывает локальный код с кодом в контейнере
      - ./python-app:/home/appuser/app
      # Папка для сохранения результатов. Файлы будут доступны на VPS в ./output_data
      - ./output_data:/home/appuser/app/output
      # Монтируем ключ SA как файл только для чтения
      - ./yandex-cloud-key.json:/etc/yc/sa_key.json:ro

    networks:
      - app-network
  nodejs:
    build:
      context: ./nodejs-app
      dockerfile: Dockerfile
    container_name: nodejs
    ports:
      - "3000:3000"
    environment:
      # Переменная для yc CLI, указывающая на ключ сервисного аккаунта
      - YC_SERVICE_ACCOUNT_KEY_FILE=/etc/yc/sa_key.json
    volumes:
      # Монтируем ключ SA как файл только для чтения
      - ./yandex-cloud-key.json:/etc/yc/sa_key.json:ro
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
