version: "3.9"

services:
  db:
    image: mysql:8.4
    container_name: mysql8
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${MYSQL_EXTERNAL_PORT:-45321}:3306"
    volumes:
      - dbdata:/var/lib/mysql                  # данные → named volume
      - ./mysql/conf.d:/etc/mysql/conf.d       # ваши *.cnf
      - ./mysql/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -uroot -p\"$${MYSQL_ROOT_PASSWORD}\" || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s
    ulimits:
      nofile:
        soft: 65536
        hard: 65536

volumes:
  dbdata:
    driver: local

