name: mysql8_yand

services:
  db:
    # Собираем образ из Dockerfile в текущей директории
    build: .
    container_name: mysql8_yand_certs
    env_file: [.env]
    environment:
      # Эта переменная будет установлена в create-yandex-docker-compose.sh
      - VM_EXTERNAL_IP
    ports:
      - "3398:3306"
    volumes:
      # ОСТАВЛЯЕМ ТОЛЬКО ЭТОТ ТОМ для хранения данных базы.
      # Все остальное теперь встроено в образ.
      - type: volume
        source: dbdata_yandex_sql_certs
        target: /var/lib/mysql
      - type: bind
        source: /app/exchange
        target: /app/exchange
      - type: bind
        source: /app/SQL_yandex_primitive2/docker_assets_primitive/certs
        target: /certs

    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -uroot -p\"$${MYSQL_ROOT_PASSWORD}\" || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s


    ulimits:
      nofile:
        soft: 65536
        hard: 65536

volumes:
  dbdata_yandex_sql_certs: