DROP USER IF EXISTS '${APP_USER}'@'%';
CREATE USER IF NOT EXISTS '${APP_USER}'@'%' IDENTIFIED BY '${APP_PASSWORD}' REQUIRE X509;
GRANT ALL PRIVILEGES ON school_sheduller.* TO '${APP_USER}'@'%';
FLUSH PRIVILEGES;
