DROP USER IF EXISTS '${APP_USER}'@'%';

CREATE USER IF NOT EXISTS '${APP_USER}'@'%'
  IDENTIFIED BY '${APP_PASSWORD}'
  REQUIRE SUBJECT '/C=RU/O=VlasovGG/CN=appuser'
          AND ISSUER  '/C=RU/O=VlasovGG/CN=${CURRENT_IP}';


GRANT ALL PRIVILEGES ON school_sheduller.* TO '${APP_USER}'@'%';
FLUSH PRIVILEGES;
