#cloud-config
package_update: false
packages:
  - curl
  - bash
  - jq
  - mc
  - ca-certificates

users:
  - name: yc-user
    groups: [sudo, docker]
    sudo: ["ALL=(ALL) NOPASSWD:ALL"]
    shell: /bin/bash

write_files:
  - path: "/usr/local/etc/yc-install.sh"
    owner: yc-user:yc-user
    permissions: "0755"
    content: |                   
      #!/bin/bash
      
      # CLI
       echo "Installing Yandex Cloud CLI"
       curl \
         --silent \
         --show-error \
         --location \
         https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash
       VM_ID=$(curl --silent http://169.254.169.254/latest/meta-data/instance-id)

      echo "SETTING YC +++++++++++++++++++++"

      yc iam key create \
        --service-account-name sc-scheduller-srv-acc \
        --output key.json \
        --folder-id b1gbgjv35qvro3lmgaci
      
      yc config profile create default
      yc config set service-account-key key.json
      yc config set cloud-id b1gib03pgvqrrfvhl3kb
      yc config set folder-id b1gbgjv35qvro3lmgaci

#      # Save YC params
#      echo "Saving YC params to the ~/.bashrc"
#      cat << EOF >> $HOME/.bashrc

    defer: true

  - path: "/app/scripts/wd.sh"
    owner: yc-user:yc-user
    permissions: "0755"
    content: |
      #!/bin/bash
      
      set -Eeuo pipefail
      for i in {1..100}
      do
        if [ -d /home/yc-user/yandex-cloud/bin ]; then
          echo "OK: /home/yc-user/yandex-cloud/bin found." | tee -a /var/log/runcmd-debug.log
          exit 0
        fi
        echo "Waiting for /home/yc-user/yandex-cloud/bin ($i)" | tee -a /var/log/runcmd-debug.log
        sleep 1
      done
      
      echo "ERROR: /home/yc-user/yandex-cloud/bin not found after 100s" | tee -a /var/log/runcmd-debug.log
      exit 1

    defer: true

runcmd:
  - [su, yc-user, -c, "/usr/local/etc/yc-install.sh"]
  - [ bash, -lc, "id -nG yc-user | grep -qw docker || usermod -aG docker yc-user" ]
  - [ bash, -lc, "install -d -m 0755 -o yc-user -g yc-user /app /app/scripts /app/exchange; install -m 0644 -o yc-user -g yc-user /dev/null /var/log/runcmd-debug.log" ]

  # Маркер перед началом
  - [ bash, -lc, 'echo "[runcmd] start" | tee -a /var/log/runcmd-debug.log' ]
  # 1) Ждём появление каталога с yc (до 5 минут) — если не появился, выходим с ошибкой
  - [bash, -lc, '/app/scripts/wd.sh' ]
  - [su, yc-user, -c, "/home/yc-user/yandex-cloud/bin/yc storage s3 cp s3://mysql8-asset-files/SQL_yandex_primitive2/scripts/download_from_yandex_s3.sh /app/scripts" ]
  - [su, yc-user, -c, "chmod +x /app/scripts/*.sh" ]
  - [su, yc-user, -c, "/app/scripts/download_from_yandex_s3.sh --bucket mysql8-asset-files --folder /app --prefix SQL_yandex_primitive2" ]
  - [su, yc-user, -c, "chmod +x /app/SQL_yandex_primitive2/scripts/*.sh" ]
  - [su, yc-user, -c, "chmod +x /app/SQL_yandex_primitive2/*.sh" ]
#  - [su, -l, yc-user, -c, "yc 2>&1 | tee -a /var/log/runcmd-debug.log" ]
  #   Принудительно загрузить профиль:
  - [ bash, -lc, 'echo "перед PATH" | tee -a /var/log/runcmd-debug.log' ]
  - [su, -l, yc-user, -c, 'echo "PATH $PATH" | tee -a /var/log/runcmd-debug.log']
#  - [ bash, -c, "export PATH=$PATH:/app/SQL_yandex_primitive2/scripts:/home/yc-user/yandex-cloud/bin; yc 2>&1 | tee -a /var/log/runcmd-debug.log" ]
  - [ su, yc-user, -c, "export PATH=$$PATH:/app/SQL_yandex_primitive2/scripts" ]

