
from input_data_OptimizationWeights_types import InputData

# ====================================================================
# Этот файл был сгенерирован автоматически скриптом generate_static_data_file.py
# Не редактируйте его вручную.
# ====================================================================

def create_timetable_data() -> InputData:
    """
    Создает объект InputData со статичными данными,
    сгенерированными из базы данных.
    """
    days = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri']
    periods = [1, 2, 3, 4, 5, 6, 7, 8]
    classes = ['2V', '2A', '2B', '3G', '3V', '3B', '3A', '4A', '4B', '4V', '4G', '5G', '5A', '5B', '5V', '6A', '6B', '6V', '7A', '7V', '7_MK', '8B', '8A', '8V', '9V', '9A', '9B', '10B', '10A', '11B', '11A']
    subjects = ['Rus', 'Lit', 'Math', 'Phys', 'Bio', 'Chem', 'Geog', 'Env', 'Alg', 'Trud', 'Art', 'Hist', 'Eng', 'PE', 'VisArt', 'Mus', 'Draw', 'Soc', 'Safe', 'NatSci', 'CS', 'Geom', 'Stat', 'SchComp', 'Relig', 'ElParms', 'Proj', 'MathAdv', 'Fin', 'Pol', 'ElRu', 'El']
    teachers = ['Gas_ASh', 'Vac_2', 'Ula_OV', 'Zhi_VI', 'Bel_IV', 'Kol_IL', 'Sol_MA', 'Los_AS', 'Vac_1', 'Ode_OG', 'Gos_EO', 'Sha_VE', 'Par_VYu', 'Osi_EM', 'Gri_TV', 'Obu_KV', 'Bad_MV', 'Var_SG', 'Kuk_EN', 'Vor_IG', 'Per_SI', 'Zue_SG', 'Got_EV', 'Sak_EV', 'Che_LN', 'Ode_DV', 'Pys_LP', 'Rad_OV', 'Put_MG', 'Sta_EV', 'Vac_IT', 'May_AYu', 'Kam_OV', 'Bul_AS', 'Kam_SI', 'Zue_M', 'Vac_fizra', 'Bur_NS', 'Fil_DM', 'Vac_Physics', 'Zal_DI']
    split_subjects = {'CS', 'Eng', 'Trud'}
    subgroup_ids = [1, 2]

    # --- Учебные планы ---
    plan_hours = {   ('10A', 'Alg'): 4,
    ('10A', 'Bio'): 1,
    ('10A', 'Chem'): 1,
    ('10A', 'El'): 1,
    ('10A', 'Geog'): 1,
    ('10A', 'Geom'): 3,
    ('10A', 'Hist'): 2,
    ('10A', 'Lit'): 3,
    ('10A', 'PE'): 4,
    ('10A', 'Phys'): 5,
    ('10A', 'Proj'): 1,
    ('10A', 'Rus'): 2,
    ('10A', 'Safe'): 1,
    ('10A', 'Soc'): 2,
    ('10A', 'Stat'): 1,
    ('10B', 'Alg'): 2,
    ('10B', 'Bio'): 1,
    ('10B', 'Chem'): 1,
    ('10B', 'El'): 2,
    ('10B', 'Geog'): 1,
    ('10B', 'Geom'): 2,
    ('10B', 'Hist'): 4,
    ('10B', 'Lit'): 3,
    ('10B', 'MathAdv'): 1,
    ('10B', 'PE'): 4,
    ('10B', 'Phys'): 2,
    ('10B', 'Proj'): 1,
    ('10B', 'Rus'): 2,
    ('10B', 'Safe'): 1,
    ('10B', 'Soc'): 2,
    ('10B', 'Stat'): 1,
    ('11A', 'Alg'): 4,
    ('11A', 'Bio'): 1,
    ('11A', 'Chem'): 1,
    ('11A', 'El'): 2,
    ('11A', 'Geog'): 1,
    ('11A', 'Geom'): 3,
    ('11A', 'Hist'): 2,
    ('11A', 'Lit'): 3,
    ('11A', 'PE'): 4,
    ('11A', 'Phys'): 5,
    ('11A', 'Rus'): 2,
    ('11A', 'Safe'): 1,
    ('11A', 'Soc'): 2,
    ('11A', 'Stat'): 1,
    ('11B', 'Alg'): 3,
    ('11B', 'Bio'): 1,
    ('11B', 'Chem'): 1,
    ('11B', 'El'): 2,
    ('11B', 'ElRu'): 1,
    ('11B', 'Geog'): 1,
    ('11B', 'Geom'): 1,
    ('11B', 'Hist'): 4,
    ('11B', 'Lit'): 3,
    ('11B', 'MathAdv'): 1,
    ('11B', 'PE'): 4,
    ('11B', 'Phys'): 2,
    ('11B', 'Rus'): 2,
    ('11B', 'Safe'): 1,
    ('11B', 'Soc'): 2,
    ('11B', 'Stat'): 1,
    ('5A', 'Bio'): 1,
    ('5A', 'Geog'): 1,
    ('5A', 'Hist'): 3,
    ('5A', 'Lit'): 3,
    ('5A', 'Math'): 6,
    ('5A', 'Mus'): 1,
    ('5A', 'PE'): 2,
    ('5A', 'Rus'): 6,
    ('5A', 'VisArt'): 1,
    ('5B', 'Bio'): 1,
    ('5B', 'Geog'): 1,
    ('5B', 'Hist'): 3,
    ('5B', 'Lit'): 3,
    ('5B', 'Math'): 6,
    ('5B', 'Mus'): 1,
    ('5B', 'PE'): 2,
    ('5B', 'Rus'): 6,
    ('5B', 'VisArt'): 1,
    ('5G', 'Bio'): 1,
    ('5G', 'Geog'): 1,
    ('5G', 'Hist'): 3,
    ('5G', 'Lit'): 3,
    ('5G', 'Math'): 6,
    ('5G', 'Mus'): 1,
    ('5G', 'PE'): 2,
    ('5G', 'Rus'): 6,
    ('5G', 'VisArt'): 1,
    ('5V', 'Bio'): 1,
    ('5V', 'Geog'): 1,
    ('5V', 'Hist'): 3,
    ('5V', 'Lit'): 3,
    ('5V', 'Math'): 6,
    ('5V', 'Mus'): 1,
    ('5V', 'PE'): 2,
    ('5V', 'Rus'): 6,
    ('5V', 'VisArt'): 1,
    ('6A', 'Bio'): 1,
    ('6A', 'Geog'): 1,
    ('6A', 'Hist'): 3,
    ('6A', 'Lit'): 3,
    ('6A', 'Math'): 6,
    ('6A', 'Mus'): 1,
    ('6A', 'PE'): 2,
    ('6A', 'Rus'): 6,
    ('6A', 'SchComp'): 1,
    ('6A', 'VisArt'): 1,
    ('6B', 'Bio'): 1,
    ('6B', 'Geog'): 1,
    ('6B', 'Hist'): 3,
    ('6B', 'Lit'): 3,
    ('6B', 'Math'): 6,
    ('6B', 'Mus'): 1,
    ('6B', 'PE'): 2,
    ('6B', 'Rus'): 6,
    ('6B', 'SchComp'): 1,
    ('6B', 'VisArt'): 1,
    ('6V', 'Bio'): 1,
    ('6V', 'Geog'): 1,
    ('6V', 'Hist'): 3,
    ('6V', 'Lit'): 3,
    ('6V', 'Math'): 6,
    ('6V', 'Mus'): 1,
    ('6V', 'PE'): 2,
    ('6V', 'Rus'): 6,
    ('6V', 'SchComp'): 1,
    ('6V', 'VisArt'): 1,
    ('7A', 'Alg'): 4,
    ('7A', 'Bio'): 1,
    ('7A', 'Geog'): 2,
    ('7A', 'Geom'): 2,
    ('7A', 'Hist'): 3,
    ('7A', 'Lit'): 2,
    ('7A', 'Mus'): 1,
    ('7A', 'PE'): 2,
    ('7A', 'Phys'): 2,
    ('7A', 'Rus'): 4,
    ('7A', 'Stat'): 1,
    ('7A', 'VisArt'): 1,
    ('7V', 'Alg'): 4,
    ('7V', 'Bio'): 1,
    ('7V', 'Geog'): 2,
    ('7V', 'Geom'): 2,
    ('7V', 'Hist'): 3,
    ('7V', 'Lit'): 2,
    ('7V', 'Mus'): 1,
    ('7V', 'PE'): 2,
    ('7V', 'Phys'): 2,
    ('7V', 'Rus'): 4,
    ('7V', 'Stat'): 1,
    ('7V', 'VisArt'): 1,
    ('7_MK', 'Alg'): 4,
    ('7_MK', 'Bio'): 1,
    ('7_MK', 'Geog'): 2,
    ('7_MK', 'Geom'): 3,
    ('7_MK', 'Hist'): 3,
    ('7_MK', 'Lit'): 2,
    ('7_MK', 'Mus'): 1,
    ('7_MK', 'PE'): 2,
    ('7_MK', 'Phys'): 2,
    ('7_MK', 'Rus'): 4,
    ('7_MK', 'Stat'): 1,
    ('7_MK', 'VisArt'): 1,
    ('8A', 'Alg'): 4,
    ('8A', 'Bio'): 2,
    ('8A', 'Chem'): 2,
    ('8A', 'Geog'): 2,
    ('8A', 'Geom'): 2,
    ('8A', 'Hist'): 2,
    ('8A', 'Lit'): 2,
    ('8A', 'Mus'): 1,
    ('8A', 'PE'): 2,
    ('8A', 'Phys'): 2,
    ('8A', 'Relig'): 1,
    ('8A', 'Rus'): 3,
    ('8A', 'Safe'): 1,
    ('8A', 'Soc'): 1,
    ('8A', 'Stat'): 1,
    ('8B', 'Alg'): 4,
    ('8B', 'Bio'): 2,
    ('8B', 'Chem'): 2,
    ('8B', 'Geog'): 2,
    ('8B', 'Geom'): 2,
    ('8B', 'Hist'): 2,
    ('8B', 'Lit'): 2,
    ('8B', 'Mus'): 1,
    ('8B', 'PE'): 2,
    ('8B', 'Phys'): 2,
    ('8B', 'Relig'): 1,
    ('8B', 'Rus'): 3,
    ('8B', 'Safe'): 1,
    ('8B', 'Soc'): 1,
    ('8B', 'Stat'): 1,
    ('8V', 'Alg'): 4,
    ('8V', 'Bio'): 2,
    ('8V', 'Chem'): 2,
    ('8V', 'Geog'): 2,
    ('8V', 'Geom'): 2,
    ('8V', 'Hist'): 2,
    ('8V', 'Lit'): 2,
    ('8V', 'Mus'): 1,
    ('8V', 'PE'): 2,
    ('8V', 'Phys'): 2,
    ('8V', 'Relig'): 1,
    ('8V', 'Rus'): 3,
    ('8V', 'Safe'): 1,
    ('8V', 'Soc'): 1,
    ('8V', 'Stat'): 1,
    ('9A', 'Alg'): 4,
    ('9A', 'Bio'): 2,
    ('9A', 'Chem'): 2,
    ('9A', 'Geog'): 2,
    ('9A', 'Geom'): 2,
    ('9A', 'Hist'): 2,
    ('9A', 'Lit'): 3,
    ('9A', 'PE'): 2,
    ('9A', 'Phys'): 3,
    ('9A', 'Rus'): 3,
    ('9A', 'Safe'): 1,
    ('9A', 'Soc'): 1,
    ('9A', 'Stat'): 1,
    ('9B', 'Alg'): 4,
    ('9B', 'Bio'): 2,
    ('9B', 'Chem'): 2,
    ('9B', 'Geog'): 2,
    ('9B', 'Geom'): 2,
    ('9B', 'Hist'): 2,
    ('9B', 'Lit'): 3,
    ('9B', 'PE'): 2,
    ('9B', 'Phys'): 3,
    ('9B', 'Rus'): 3,
    ('9B', 'Safe'): 1,
    ('9B', 'Soc'): 1,
    ('9B', 'Stat'): 1,
    ('9V', 'Alg'): 4,
    ('9V', 'Bio'): 2,
    ('9V', 'Chem'): 2,
    ('9V', 'Geog'): 2,
    ('9V', 'Geom'): 2,
    ('9V', 'Hist'): 2,
    ('9V', 'Lit'): 3,
    ('9V', 'PE'): 2,
    ('9V', 'Phys'): 3,
    ('9V', 'Rus'): 3,
    ('9V', 'Safe'): 1,
    ('9V', 'Soc'): 1,
    ('9V', 'Stat'): 1}
    subgroup_plan_hours = {   ('10A', 'CS', 1): 1,
    ('10A', 'CS', 2): 1,
    ('10A', 'Eng', 1): 3,
    ('10A', 'Eng', 2): 3,
    ('10B', 'CS', 1): 1,
    ('10B', 'CS', 2): 1,
    ('10B', 'Eng', 1): 5,
    ('10B', 'Eng', 2): 5,
    ('11A', 'CS', 1): 1,
    ('11A', 'CS', 2): 1,
    ('11A', 'Eng', 1): 3,
    ('11A', 'Eng', 2): 3,
    ('11B', 'CS', 1): 1,
    ('11B', 'CS', 2): 1,
    ('11B', 'Eng', 1): 5,
    ('11B', 'Eng', 2): 5,
    ('2A', 'Eng', 1): 2,
    ('2A', 'Eng', 2): 2,
    ('2B', 'Eng', 1): 2,
    ('2B', 'Eng', 2): 2,
    ('2V', 'Eng', 1): 2,
    ('2V', 'Eng', 2): 2,
    ('3A', 'Eng', 1): 2,
    ('3A', 'Eng', 2): 2,
    ('3B', 'Eng', 1): 2,
    ('3B', 'Eng', 2): 2,
    ('3G', 'Eng', 1): 2,
    ('3G', 'Eng', 2): 2,
    ('3V', 'Eng', 1): 2,
    ('3V', 'Eng', 2): 2,
    ('4A', 'Eng', 1): 2,
    ('4A', 'Eng', 2): 2,
    ('4B', 'Eng', 1): 2,
    ('4B', 'Eng', 2): 2,
    ('4G', 'Eng', 1): 2,
    ('4G', 'Eng', 2): 2,
    ('4V', 'Eng', 1): 2,
    ('4V', 'Eng', 2): 2,
    ('5A', 'Eng', 1): 3,
    ('5A', 'Eng', 2): 3,
    ('5A', 'Trud', 1): 2,
    ('5A', 'Trud', 2): 2,
    ('5B', 'Eng', 1): 3,
    ('5B', 'Eng', 2): 3,
    ('5B', 'Trud', 1): 2,
    ('5B', 'Trud', 2): 2,
    ('5G', 'Eng', 1): 3,
    ('5G', 'Eng', 2): 3,
    ('5G', 'Trud', 1): 2,
    ('5G', 'Trud', 2): 2,
    ('5V', 'Eng', 1): 3,
    ('5V', 'Eng', 2): 3,
    ('5V', 'Trud', 1): 2,
    ('5V', 'Trud', 2): 2,
    ('6A', 'Eng', 1): 3,
    ('6A', 'Eng', 2): 3,
    ('6A', 'Trud', 1): 2,
    ('6A', 'Trud', 2): 2,
    ('6B', 'Eng', 1): 3,
    ('6B', 'Eng', 2): 3,
    ('6B', 'Trud', 1): 2,
    ('6B', 'Trud', 2): 2,
    ('6V', 'Eng', 1): 3,
    ('6V', 'Eng', 2): 3,
    ('6V', 'Trud', 1): 2,
    ('6V', 'Trud', 2): 2,
    ('7A', 'CS', 1): 1,
    ('7A', 'CS', 2): 1,
    ('7A', 'Eng', 1): 4,
    ('7A', 'Eng', 2): 4,
    ('7A', 'Trud', 1): 2,
    ('7A', 'Trud', 2): 2,
    ('7V', 'CS', 1): 1,
    ('7V', 'CS', 2): 1,
    ('7V', 'Eng', 1): 4,
    ('7V', 'Eng', 2): 4,
    ('7V', 'Trud', 1): 2,
    ('7V', 'Trud', 2): 2,
    ('7_MK', 'CS', 1): 1,
    ('7_MK', 'CS', 2): 1,
    ('7_MK', 'Eng', 1): 3,
    ('7_MK', 'Eng', 2): 3,
    ('7_MK', 'Trud', 1): 2,
    ('7_MK', 'Trud', 2): 2,
    ('8A', 'CS', 1): 1,
    ('8A', 'CS', 2): 1,
    ('8A', 'Eng', 1): 3,
    ('8A', 'Eng', 2): 3,
    ('8A', 'Trud', 1): 1,
    ('8A', 'Trud', 2): 1,
    ('8B', 'CS', 1): 1,
    ('8B', 'CS', 2): 1,
    ('8B', 'Eng', 1): 3,
    ('8B', 'Eng', 2): 3,
    ('8B', 'Trud', 1): 1,
    ('8B', 'Trud', 2): 1,
    ('8V', 'CS', 1): 1,
    ('8V', 'CS', 2): 1,
    ('8V', 'Eng', 1): 3,
    ('8V', 'Eng', 2): 3,
    ('8V', 'Trud', 1): 1,
    ('8V', 'Trud', 2): 1,
    ('9A', 'CS', 1): 1,
    ('9A', 'CS', 2): 1,
    ('9A', 'Eng', 1): 3,
    ('9A', 'Eng', 2): 3,
    ('9A', 'Trud', 1): 1,
    ('9A', 'Trud', 2): 1,
    ('9B', 'CS', 1): 1,
    ('9B', 'CS', 2): 1,
    ('9B', 'Eng', 1): 3,
    ('9B', 'Eng', 2): 3,
    ('9B', 'Trud', 1): 1,
    ('9B', 'Trud', 2): 1,
    ('9V', 'CS', 1): 1,
    ('9V', 'CS', 2): 1,
    ('9V', 'Eng', 1): 3,
    ('9V', 'Eng', 2): 3,
    ('9V', 'Trud', 1): 1,
    ('9V', 'Trud', 2): 1}

    # --- Закрепления учителей ---
    assigned_teacher = {   ('10A', 'Alg'): 'Kol_IL',
    ('10A', 'Bio'): 'Vor_IG',
    ('10A', 'Chem'): 'Var_SG',
    ('10A', 'El'): 'Kol_IL',
    ('10A', 'Geog'): 'Sak_EV',
    ('10A', 'Geom'): 'Kol_IL',
    ('10A', 'Hist'): 'Vac_IT',
    ('10A', 'Lit'): 'Che_LN',
    ('10A', 'PE'): 'Zue_M',
    ('10A', 'Phys'): 'Ula_OV',
    ('10A', 'Proj'): 'Vor_IG',
    ('10A', 'Rus'): 'Che_LN',
    ('10A', 'Safe'): 'Fil_DM',
    ('10A', 'Soc'): 'Vac_IT',
    ('10A', 'Stat'): 'Kol_IL',
    ('10B', 'Alg'): 'Put_MG',
    ('10B', 'Bio'): 'Vor_IG',
    ('10B', 'Chem'): 'Var_SG',
    ('10B', 'El'): 'Vac_IT',
    ('10B', 'Geog'): 'Sak_EV',
    ('10B', 'Geom'): 'Put_MG',
    ('10B', 'Hist'): 'Bad_MV',
    ('10B', 'Lit'): 'Che_LN',
    ('10B', 'MathAdv'): 'Put_MG',
    ('10B', 'PE'): 'Zue_M',
    ('10B', 'Phys'): 'Vac_Physics',
    ('10B', 'Proj'): 'Vac_IT',
    ('10B', 'Rus'): 'Che_LN',
    ('10B', 'Safe'): 'Fil_DM',
    ('10B', 'Soc'): 'Vac_IT',
    ('10B', 'Stat'): 'Put_MG',
    ('11A', 'Alg'): 'Kol_IL',
    ('11A', 'Bio'): 'Vor_IG',
    ('11A', 'Chem'): 'Var_SG',
    ('11A', 'El'): 'Kol_IL',
    ('11A', 'Geog'): 'Sak_EV',
    ('11A', 'Geom'): 'Kol_IL',
    ('11A', 'Hist'): 'Vac_IT',
    ('11A', 'Lit'): 'Bel_IV',
    ('11A', 'PE'): 'Zue_M',
    ('11A', 'Phys'): 'Ula_OV',
    ('11A', 'Rus'): 'Bel_IV',
    ('11A', 'Safe'): 'Fil_DM',
    ('11A', 'Soc'): 'Vac_IT',
    ('11A', 'Stat'): 'Kol_IL',
    ('11B', 'Alg'): 'Put_MG',
    ('11B', 'Bio'): 'Vor_IG',
    ('11B', 'Chem'): 'Var_SG',
    ('11B', 'El'): 'Vac_IT',
    ('11B', 'ElRu'): 'Ode_DV',
    ('11B', 'Geog'): 'Sak_EV',
    ('11B', 'Geom'): 'Put_MG',
    ('11B', 'Hist'): 'Bad_MV',
    ('11B', 'Lit'): 'Ode_DV',
    ('11B', 'MathAdv'): 'Put_MG',
    ('11B', 'PE'): 'Zue_M',
    ('11B', 'Phys'): 'Vac_Physics',
    ('11B', 'Rus'): 'Ode_DV',
    ('11B', 'Safe'): 'Fil_DM',
    ('11B', 'Soc'): 'Osi_EM',
    ('11B', 'Stat'): 'Put_MG',
    ('5A', 'Bio'): 'Vor_IG',
    ('5A', 'Geog'): 'Sak_EV',
    ('5A', 'Hist'): 'Osi_EM',
    ('5A', 'Lit'): 'Bel_IV',
    ('5A', 'Math'): 'Put_MG',
    ('5A', 'Mus'): 'Gas_ASh',
    ('5A', 'PE'): 'Vac_fizra',
    ('5A', 'Rus'): 'Bel_IV',
    ('5A', 'VisArt'): 'Kam_SI',
    ('5B', 'Bio'): 'Vor_IG',
    ('5B', 'Geog'): 'Sak_EV',
    ('5B', 'Hist'): 'Osi_EM',
    ('5B', 'Lit'): 'Vac_2',
    ('5B', 'Math'): 'Zal_DI',
    ('5B', 'Mus'): 'Gas_ASh',
    ('5B', 'PE'): 'Vac_fizra',
    ('5B', 'Rus'): 'Vac_2',
    ('5B', 'VisArt'): 'Kam_SI',
    ('5G', 'Bio'): 'Vor_IG',
    ('5G', 'Geog'): 'Sak_EV',
    ('5G', 'Hist'): 'Sta_EV',
    ('5G', 'Lit'): 'Vac_2',
    ('5G', 'Math'): 'Gri_TV',
    ('5G', 'Mus'): 'Gas_ASh',
    ('5G', 'PE'): 'Bur_NS',
    ('5G', 'Rus'): 'Vac_2',
    ('5G', 'VisArt'): 'Kam_SI',
    ('5V', 'Bio'): 'Vor_IG',
    ('5V', 'Geog'): 'Sak_EV',
    ('5V', 'Hist'): 'Sta_EV',
    ('5V', 'Lit'): 'Vac_1',
    ('5V', 'Math'): 'Zal_DI',
    ('5V', 'Mus'): 'Gas_ASh',
    ('5V', 'PE'): 'Bur_NS',
    ('5V', 'Rus'): 'Vac_1',
    ('5V', 'VisArt'): 'Kam_SI',
    ('6A', 'Bio'): 'Vor_IG',
    ('6A', 'Geog'): 'Sak_EV',
    ('6A', 'Hist'): 'Sta_EV',
    ('6A', 'Lit'): 'Ode_DV',
    ('6A', 'Math'): 'Rad_OV',
    ('6A', 'Mus'): 'Gas_ASh',
    ('6A', 'PE'): 'Bur_NS',
    ('6A', 'Rus'): 'Bel_IV',
    ('6A', 'SchComp'): 'Sta_EV',
    ('6A', 'VisArt'): 'Kam_SI',
    ('6B', 'Bio'): 'Vor_IG',
    ('6B', 'Geog'): 'Sak_EV',
    ('6B', 'Hist'): 'Sta_EV',
    ('6B', 'Lit'): 'Vac_1',
    ('6B', 'Math'): 'Sol_MA',
    ('6B', 'Mus'): 'Gas_ASh',
    ('6B', 'PE'): 'Bur_NS',
    ('6B', 'Rus'): 'Vac_1',
    ('6B', 'SchComp'): 'Sta_EV',
    ('6B', 'VisArt'): 'Kam_SI',
    ('6V', 'Bio'): 'Vor_IG',
    ('6V', 'Geog'): 'Sak_EV',
    ('6V', 'Hist'): 'Bad_MV',
    ('6V', 'Lit'): 'Pys_LP',
    ('6V', 'Math'): 'Sol_MA',
    ('6V', 'Mus'): 'Gas_ASh',
    ('6V', 'PE'): 'Bur_NS',
    ('6V', 'Rus'): 'Pys_LP',
    ('6V', 'SchComp'): 'Sta_EV',
    ('6V', 'VisArt'): 'Kam_SI',
    ('7A', 'Alg'): 'Rad_OV',
    ('7A', 'Bio'): 'Vor_IG',
    ('7A', 'Geog'): 'Sak_EV',
    ('7A', 'Geom'): 'Rad_OV',
    ('7A', 'Hist'): 'Vac_IT',
    ('7A', 'Lit'): 'Ode_DV',
    ('7A', 'Mus'): 'Gas_ASh',
    ('7A', 'PE'): 'Vac_fizra',
    ('7A', 'Phys'): 'Ula_OV',
    ('7A', 'Rus'): 'Ode_DV',
    ('7A', 'Stat'): 'Rad_OV',
    ('7A', 'VisArt'): 'Kam_SI',
    ('7V', 'Alg'): 'Sol_MA',
    ('7V', 'Bio'): 'Vor_IG',
    ('7V', 'Geog'): 'Sak_EV',
    ('7V', 'Geom'): 'Sol_MA',
    ('7V', 'Hist'): 'Sta_EV',
    ('7V', 'Lit'): 'Pys_LP',
    ('7V', 'Mus'): 'Gas_ASh',
    ('7V', 'PE'): 'Bur_NS',
    ('7V', 'Phys'): 'Ula_OV',
    ('7V', 'Rus'): 'Pys_LP',
    ('7V', 'Stat'): 'Sol_MA',
    ('7V', 'VisArt'): 'Kam_SI',
    ('7_MK', 'Alg'): 'Rad_OV',
    ('7_MK', 'Bio'): 'Vor_IG',
    ('7_MK', 'Geog'): 'Sak_EV',
    ('7_MK', 'Geom'): 'Rad_OV',
    ('7_MK', 'Hist'): 'Osi_EM',
    ('7_MK', 'Lit'): 'Vac_1',
    ('7_MK', 'Mus'): 'Gas_ASh',
    ('7_MK', 'PE'): 'Vac_fizra',
    ('7_MK', 'Phys'): 'Ula_OV',
    ('7_MK', 'Rus'): 'Vac_1',
    ('7_MK', 'Stat'): 'Rad_OV',
    ('7_MK', 'VisArt'): 'Kam_SI',
    ('8A', 'Alg'): 'Kol_IL',
    ('8A', 'Bio'): 'Vor_IG',
    ('8A', 'Chem'): 'Var_SG',
    ('8A', 'Geog'): 'Sak_EV',
    ('8A', 'Geom'): 'Kol_IL',
    ('8A', 'Hist'): 'Bad_MV',
    ('8A', 'Lit'): 'Che_LN',
    ('8A', 'Mus'): 'Gas_ASh',
    ('8A', 'PE'): 'Bur_NS',
    ('8A', 'Phys'): 'Vac_Physics',
    ('8A', 'Relig'): 'Sta_EV',
    ('8A', 'Rus'): 'Che_LN',
    ('8A', 'Safe'): 'Fil_DM',
    ('8A', 'Soc'): 'Bad_MV',
    ('8A', 'Stat'): 'Kol_IL',
    ('8B', 'Alg'): 'Bul_AS',
    ('8B', 'Bio'): 'Vor_IG',
    ('8B', 'Chem'): 'Var_SG',
    ('8B', 'Geog'): 'Sak_EV',
    ('8B', 'Geom'): 'Bul_AS',
    ('8B', 'Hist'): 'Bad_MV',
    ('8B', 'Lit'): 'Che_LN',
    ('8B', 'Mus'): 'Gas_ASh',
    ('8B', 'PE'): 'Bur_NS',
    ('8B', 'Phys'): 'Vac_Physics',
    ('8B', 'Relig'): 'Sta_EV',
    ('8B', 'Rus'): 'Che_LN',
    ('8B', 'Safe'): 'Fil_DM',
    ('8B', 'Soc'): 'Bad_MV',
    ('8B', 'Stat'): 'Bul_AS',
    ('8V', 'Alg'): 'Sol_MA',
    ('8V', 'Bio'): 'Vor_IG',
    ('8V', 'Chem'): 'Var_SG',
    ('8V', 'Geog'): 'Sak_EV',
    ('8V', 'Geom'): 'Sol_MA',
    ('8V', 'Hist'): 'Vac_IT',
    ('8V', 'Lit'): 'Pys_LP',
    ('8V', 'Mus'): 'Gas_ASh',
    ('8V', 'PE'): 'Bur_NS',
    ('8V', 'Phys'): 'Vac_Physics',
    ('8V', 'Relig'): 'Sta_EV',
    ('8V', 'Rus'): 'Pys_LP',
    ('8V', 'Safe'): 'Fil_DM',
    ('8V', 'Soc'): 'Vac_IT',
    ('8V', 'Stat'): 'Sol_MA',
    ('9A', 'Alg'): 'Put_MG',
    ('9A', 'Bio'): 'Vor_IG',
    ('9A', 'Chem'): 'Var_SG',
    ('9A', 'Geog'): 'Sak_EV',
    ('9A', 'Geom'): 'Put_MG',
    ('9A', 'Hist'): 'Osi_EM',
    ('9A', 'Lit'): 'Ode_DV',
    ('9A', 'PE'): 'Bur_NS',
    ('9A', 'Phys'): 'Ula_OV',
    ('9A', 'Rus'): 'Ode_DV',
    ('9A', 'Safe'): 'Fil_DM',
    ('9A', 'Soc'): 'Osi_EM',
    ('9A', 'Stat'): 'Put_MG',
    ('9B', 'Alg'): 'Bul_AS',
    ('9B', 'Bio'): 'Vor_IG',
    ('9B', 'Chem'): 'Var_SG',
    ('9B', 'Geog'): 'Sak_EV',
    ('9B', 'Geom'): 'Bul_AS',
    ('9B', 'Hist'): 'Osi_EM',
    ('9B', 'Lit'): 'Bel_IV',
    ('9B', 'PE'): 'Vac_fizra',
    ('9B', 'Phys'): 'Ula_OV',
    ('9B', 'Rus'): 'Bel_IV',
    ('9B', 'Safe'): 'Fil_DM',
    ('9B', 'Soc'): 'Osi_EM',
    ('9B', 'Stat'): 'Bul_AS',
    ('9V', 'Alg'): 'Sol_MA',
    ('9V', 'Bio'): 'Vor_IG',
    ('9V', 'Chem'): 'Var_SG',
    ('9V', 'Geog'): 'Sak_EV',
    ('9V', 'Geom'): 'Sol_MA',
    ('9V', 'Hist'): 'Bad_MV',
    ('9V', 'Lit'): 'Che_LN',
    ('9V', 'PE'): 'Vac_fizra',
    ('9V', 'Phys'): 'Ula_OV',
    ('9V', 'Rus'): 'Che_LN',
    ('9V', 'Safe'): 'Fil_DM',
    ('9V', 'Soc'): 'Bad_MV',
    ('9V', 'Stat'): 'Sol_MA'}
    subgroup_assigned_teacher = {   ('10A', 'CS', 1): 'Bul_AS',
    ('10A', 'CS', 2): 'Bul_AS',
    ('10A', 'Eng', 1): 'Zhi_VI',
    ('10A', 'Eng', 2): 'Par_VYu',
    ('10B', 'CS', 1): 'Bul_AS',
    ('10B', 'CS', 2): 'Bul_AS',
    ('10B', 'Eng', 1): 'Zhi_VI',
    ('10B', 'Eng', 2): 'Gos_EO',
    ('11A', 'CS', 1): 'Bul_AS',
    ('11A', 'CS', 2): 'Bul_AS',
    ('11A', 'Eng', 1): 'Got_EV',
    ('11A', 'Eng', 2): 'Par_VYu',
    ('11B', 'CS', 1): 'Bul_AS',
    ('11B', 'CS', 2): 'Bul_AS',
    ('11B', 'Eng', 1): 'Zhi_VI',
    ('11B', 'Eng', 2): 'Par_VYu',
    ('2A', 'Eng', 1): 'Sha_VE',
    ('2A', 'Eng', 2): 'Zue_SG',
    ('2B', 'Eng', 1): 'Sha_VE',
    ('2B', 'Eng', 2): 'Zue_SG',
    ('2V', 'Eng', 1): 'Gos_EO',
    ('2V', 'Eng', 2): 'Sha_VE',
    ('3A', 'Eng', 1): 'Got_EV',
    ('3A', 'Eng', 2): 'Gos_EO',
    ('3B', 'Eng', 1): 'Got_EV',
    ('3B', 'Eng', 2): 'Sha_VE',
    ('3G', 'Eng', 1): 'Sha_VE',
    ('3G', 'Eng', 2): 'Gos_EO',
    ('3V', 'Eng', 1): 'Got_EV',
    ('3V', 'Eng', 2): 'Sha_VE',
    ('4A', 'Eng', 1): 'Got_EV',
    ('4A', 'Eng', 2): 'Gos_EO',
    ('4B', 'Eng', 1): 'Par_VYu',
    ('4B', 'Eng', 2): 'Gos_EO',
    ('4G', 'Eng', 1): 'Sha_VE',
    ('4G', 'Eng', 2): 'Par_VYu',
    ('4V', 'Eng', 1): 'Zue_SG',
    ('4V', 'Eng', 2): 'Sha_VE',
    ('5A', 'Eng', 1): 'Got_EV',
    ('5A', 'Eng', 2): 'May_AYu',
    ('5A', 'Trud', 1): 'Gri_TV',
    ('5A', 'Trud', 2): 'Kam_OV',
    ('5B', 'Eng', 1): 'Got_EV',
    ('5B', 'Eng', 2): 'Sha_VE',
    ('5B', 'Trud', 1): 'Gri_TV',
    ('5B', 'Trud', 2): 'Kam_OV',
    ('5G', 'Eng', 1): 'Zhi_VI',
    ('5G', 'Eng', 2): 'Sha_VE',
    ('5G', 'Trud', 1): 'Gri_TV',
    ('5G', 'Trud', 2): 'Kam_OV',
    ('5V', 'Eng', 1): 'Sha_VE',
    ('5V', 'Eng', 2): 'Zhi_VI',
    ('5V', 'Trud', 1): 'Gri_TV',
    ('5V', 'Trud', 2): 'Kam_OV',
    ('6A', 'Eng', 1): 'Got_EV',
    ('6A', 'Eng', 2): 'May_AYu',
    ('6A', 'Trud', 1): 'Gri_TV',
    ('6A', 'Trud', 2): 'Kam_OV',
    ('6B', 'Eng', 1): 'Got_EV',
    ('6B', 'Eng', 2): 'Par_VYu',
    ('6B', 'Trud', 1): 'Gri_TV',
    ('6B', 'Trud', 2): 'Kam_OV',
    ('6V', 'Eng', 1): 'Got_EV',
    ('6V', 'Eng', 2): 'Par_VYu',
    ('6V', 'Trud', 1): 'Gri_TV',
    ('6V', 'Trud', 2): 'Kam_OV',
    ('7A', 'CS', 1): 'Kam_OV',
    ('7A', 'CS', 2): 'Kam_OV',
    ('7A', 'Eng', 1): 'Zhi_VI',
    ('7A', 'Eng', 2): 'Kuk_EN',
    ('7A', 'Trud', 1): 'Gri_TV',
    ('7A', 'Trud', 2): 'Kam_SI',
    ('7V', 'CS', 1): 'Kam_OV',
    ('7V', 'CS', 2): 'Kam_OV',
    ('7V', 'Eng', 1): 'Zue_SG',
    ('7V', 'Eng', 2): 'Kuk_EN',
    ('7V', 'Trud', 1): 'Gri_TV',
    ('7V', 'Trud', 2): 'Kam_SI',
    ('7_MK', 'CS', 1): 'Kam_OV',
    ('7_MK', 'CS', 2): 'Kam_OV',
    ('7_MK', 'Eng', 1): 'Zue_SG',
    ('7_MK', 'Eng', 2): 'Par_VYu',
    ('7_MK', 'Trud', 1): 'Gri_TV',
    ('7_MK', 'Trud', 2): 'Kam_SI',
    ('8A', 'CS', 1): 'Kam_OV',
    ('8A', 'CS', 2): 'Kam_OV',
    ('8A', 'Eng', 1): 'Zue_SG',
    ('8A', 'Eng', 2): 'Got_EV',
    ('8A', 'Trud', 1): 'Gri_TV',
    ('8A', 'Trud', 2): 'Kam_SI',
    ('8B', 'CS', 1): 'Kam_OV',
    ('8B', 'CS', 2): 'Kam_OV',
    ('8B', 'Eng', 1): 'Zue_SG',
    ('8B', 'Eng', 2): 'Gos_EO',
    ('8B', 'Trud', 1): 'Gri_TV',
    ('8B', 'Trud', 2): 'Kam_SI',
    ('8V', 'CS', 1): 'Kam_OV',
    ('8V', 'CS', 2): 'Kam_OV',
    ('8V', 'Eng', 1): 'Zue_SG',
    ('8V', 'Eng', 2): 'Gos_EO',
    ('8V', 'Trud', 1): 'Gri_TV',
    ('8V', 'Trud', 2): 'Kam_SI',
    ('9A', 'CS', 1): 'Bul_AS',
    ('9A', 'CS', 2): 'Bul_AS',
    ('9A', 'Eng', 1): 'Zhi_VI',
    ('9A', 'Eng', 2): 'Par_VYu',
    ('9A', 'Trud', 1): 'Gri_TV',
    ('9A', 'Trud', 2): 'Kam_SI',
    ('9B', 'CS', 1): 'Bul_AS',
    ('9B', 'CS', 2): 'Bul_AS',
    ('9B', 'Eng', 1): 'Zhi_VI',
    ('9B', 'Eng', 2): 'May_AYu',
    ('9B', 'Trud', 1): 'Gri_TV',
    ('9B', 'Trud', 2): 'Kam_SI',
    ('9V', 'CS', 1): 'Bul_AS',
    ('9V', 'CS', 2): 'Bul_AS',
    ('9V', 'Eng', 1): 'Kuk_EN',
    ('9V', 'Eng', 2): 'Gos_EO',
    ('9V', 'Trud', 1): 'Gri_TV',
    ('9V', 'Trud', 2): 'Kam_SI'}

    # --- Ограничения ---
    days_off = {'Osi_EM': {'Mon', 'Tue'}}
    forbidden_slots = {   ('10A', 'Mon', 1),
    ('10B', 'Mon', 1),
    ('11A', 'Mon', 1),
    ('11B', 'Mon', 1),
    ('2A', 'Mon', 1),
    ('2B', 'Mon', 1),
    ('2V', 'Mon', 1),
    ('3A', 'Mon', 1),
    ('3B', 'Mon', 1),
    ('3G', 'Mon', 1),
    ('3V', 'Mon', 1),
    ('4A', 'Mon', 1),
    ('4B', 'Mon', 1),
    ('4G', 'Mon', 1),
    ('4V', 'Mon', 1),
    ('5A', 'Mon', 1),
    ('5B', 'Mon', 1),
    ('5G', 'Mon', 1),
    ('5V', 'Mon', 1),
    ('6A', 'Mon', 1),
    ('6B', 'Mon', 1),
    ('6V', 'Mon', 1),
    ('7A', 'Mon', 1),
    ('7V', 'Mon', 1),
    ('7_MK', 'Mon', 1),
    ('8A', 'Mon', 1),
    ('8B', 'Mon', 1),
    ('8V', 'Mon', 1),
    ('9A', 'Mon', 1),
    ('9B', 'Mon', 1),
    ('9V', 'Mon', 1)}

    # --- Мягкие цели ---
    class_slot_weight = {('5A', 'Fri', 6): 5, ('5A', 'Fri', 7): 10}
    teacher_slot_weight = {('Vac_2', 'Tue', 1): 8}
    class_subject_day_weight = {('5A', 'Geog', 'Mon'): 6}

    # --- Совместимости ---
    compatible_pairs = {('CS', 'Eng')}

    return InputData(
        days=days,
        periods=periods,
        classes=classes,
        subjects=subjects,
        teachers=teachers,
        split_subjects=split_subjects,
        subgroup_ids=subgroup_ids,
        plan_hours=plan_hours,
        subgroup_plan_hours=subgroup_plan_hours,
        assigned_teacher=assigned_teacher,
        subgroup_assigned_teacher=subgroup_assigned_teacher,
        days_off=days_off,
        forbidden_slots=forbidden_slots,
        class_slot_weight=class_slot_weight,
        teacher_slot_weight=teacher_slot_weight,
        class_subject_day_weight=class_subject_day_weight,
        compatible_pairs=compatible_pairs
    )
